name: Deploy React App to VM

on:
  push:
    branches:
      - main  

env:
  IMAGE_NAME: payment-integration-fe
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}

  deploy-to-vm:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST}} >> ~/.ssh/known_hosts

      - name: Pull and restart container on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin &&
            docker pull ${{ secrets.DOCKER_USERNAME }}/payment-integration-fe:${{ github.sha }} &&
            docker stop payment-integration-fe || true &&
            docker rm payment-integration-fe || true &&
            docker run -d --name payment-integration-fe -p 3000:80 ${{ secrets.DOCKER_USERNAME }}/payment-integration-fe:${{ github.sha }}
          "
